### PR TITLE
Fix escaping in content_for

### PR DESCRIPTION
**Pull request by ghazel**
From: https://rails.lighthouseapp.com/projects/8994/tickets/6302-content_for-and-xss-bug

### CODE REVIEW

**Comment by spastorino** [comment]
ghazel, seems ok but can you add a test case?.
Thanks :).

**Comment by ghazel** [comment]
I couldn't get the tests to run, because:

```
C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-2.3.10/lib/active_support/dependencies.rb:466:in `load_missing_constant': uninitialized constant ActionView::TestCase (NameError)
        from C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-2.3.10/lib/active_support/dependencies.rb:106:in `const_missing'
        from ./test/active_record_helper_test.rb:3
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `load'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `each'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5
rake aborted!
```

**Comment by ghazel** [comment]
There you go.

**Comment by spastorino** [comment]
Pushed, thanks

**Pull request closed without merging**
